{% set name = "django-plotly-wagtail" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-plotly-wagtail-{{ version }}.tar.gz
  sha256: 4603f0f27af904d8b0febbecc14ee9ae8610a3bd08040e1c0cee94cb3d872d48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - django >3.2
    - django-plotly-dash
    - wagtail
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - dpwagtail
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/GibbsConsulting/django-plotly-wagtail
  summary: Django Wagtail use of django-plotly-dash and plotly dash
  dev_url: https://gitlab.com/GibbsConsulting/django-plotly-wagtail
  license: NGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
